#!/usr/bin/env bash
#configuration of the Nginx server to include a redirect page
#the redirection displays "301 moved permanently"

apt-get updte
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html>index.html
print %s "server {
   listen 80;
   listen [::]: 80 default server;
   root   /etc/nginx/html;
   index  index.html index.htm;
   location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
   }
}" > /etc/nginx/sites-available/default

service  nginx restart