#!/usr/bin/env bash
#configuration of the Nginx server to include a redirect page
#the redirection displays "301 moved permanently"

apt-get updte
apt-get install -y nginx
ufw allow 'Nginx HTTP'

echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

service  nginx restart
