#!/usr/bin/env bash
#configuring the SSH client to connect to a server

Host *
     PasswordAuthentication no
     IdentityFile ~/.ssh/school
     sendEnv LANG LC_*
     HashKnownHosts yes
     GSSAPIAuthentication yes
     HostName 100.26.10.86
     User ubuntu